// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_products_name_ from "./routes/api/products/[name].ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $hello from "./routes/hello.tsx";
import * as $index_old from "./routes/index.old.tsx";
import * as $index from "./routes/index.tsx";
import * as $products_name_ from "./routes/products/[name].tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/products/[name].ts": $api_products_name_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/hello.tsx": $hello,
    "./routes/index.old.tsx": $index_old,
    "./routes/index.tsx": $index,
    "./routes/products/[name].tsx": $products_name_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Navbar.tsx": $Navbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
